name: python_import
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - attrs=25.4.0=py312h06a4308_2
  - blas=1.0=openblas
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py312haa0f9ac_1
  - branca=0.8.1=py312h06a4308_1
  - brotlicffi=1.2.0.0=py312h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_1
  - charset-normalizer=3.4.4=py312h06a4308_0
  - click=8.1.8=py312h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - contourpy=1.3.3=py312hdb19cb5_0
  - cycler=0.12.1=py312h06a4308_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py312hbdd6827_1
  - et_xmlfile=2.0.0=py312h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - fiona=1.10.1=py312h7354ed3_2
  - folium=0.20.0=py312h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.61.0=py312h47b2149_0
  - freetype=2.13.3=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.16=h9fb5f84_0
  - gdal=3.11.4=py312hf50df08_9
  - geoalchemy2=0.18.0=py312h06a4308_0
  - geopandas=1.1.1=py312h06a4308_0
  - geopandas-base=1.1.1=py312h06a4308_0
  - geos=3.10.6=h6a678d5_0
  - geotiff=1.7.0=ha59944b_4
  - gettext=0.21.0=hedfda30_2
  - giflib=5.2.2=h5eee18b_0
  - git=2.51.0=pl5382h9046301_1
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.2.4=py312hbdd6827_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py312h06a4308_0
  - imageio=2.37.2=py312h7040dfc_0
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.3=py312h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json-c=0.18=hee96239_0
  - kiwisolver=1.4.9=py312h24d9097_0
  - lazy_loader=0.4=py312h06a4308_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.17.0=hc93bc37_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal-core=3.11.4=hc92985d_0
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkml=1.3.0=h096b73e_7
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libsodium=1.0.20=heac8642_0
  - libspatialite=5.1.0=h798b768_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lxml=5.3.0=py312hd70a998_2
  - lz4-c=1.9.4=h6a678d5_1
  - mapclassify=2.10.0=py312h06a4308_0
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib=3.10.8=py312h06a4308_0
  - matplotlib-base=3.10.8=py312h8a257da_0
  - mesalib=25.1.5=h31e3550_0
  - minizip=4.0.3=hf59b114_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - ncurses=6.5=h7934f7d_0
  - networkx=3.6.1=py312h06a4308_0
  - numexpr=2.14.1=py312ha5a4a6c_0
  - numpy=2.4.1=py312h35d6838_0
  - numpy-base=2.4.1=py312h4bc27c9_0
  - openldap=2.6.10=he9288cc_1
  - openpyxl=3.1.5=py312h5eee18b_1
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py312h06a4308_1
  - pandas=2.3.3=py312h23c847b_1
  - pcre2=10.46=hf426167_0
  - perl=5.42.0=0_h47b2149_perl5
  - pillow=12.0.0=py312h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - proj=9.3.1=h4591001_1
  - psycopg2=2.9.11=py312hc5427ea_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py312h06a4308_0
  - pyogrio=0.10.0=py312h16bd0e6_1
  - pyparsing=3.2.5=py312h06a4308_0
  - pyproj=3.6.1=py312h6268720_1
  - pyqt=6.9.1=py312hc79087c_0
  - pyqt6-sip=13.10.2=py312hee96239_0
  - pysocks=1.7.1=py312h06a4308_1
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=py312h06a4308_0
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py312h06a4308_1
  - scikit-image=0.26.0=py312h7354ed3_0
  - scikit-learn=1.8.0=py312h86c3e14_0
  - scipy=1.16.3=py312he2bc341_0
  - setuptools=80.9.0=py312h06a4308_0
  - shapely=2.1.2=py312h3e784f6_0
  - sip=6.12.0=py312h7934f7d_0
  - six=1.17.0=py312h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlalchemy=2.0.45=py312h357f0b5_0
  - sqlite=3.51.1=he0a8d7e_0
  - threadpoolctl=3.5.0=py312h7040dfc_1
  - tifffile=2025.12.20=py312h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py312h47b2149_0
  - typing=3.10.0.0=py312h06a4308_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025c=he532380_0
  - uriparser=0.9.8=h451ca9b_0
  - urllib3=2.6.3=py312h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xerces-c=3.3.0=ha155076_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xlrd=2.0.2=pyhd3eb1b0_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.4.0=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
